test: shrink aliyun raw image size

diff --git a/.github/workflows/build-ova.yml b/.github/workflows/build-ova.yml
--- a/.github/workflows/build-ova.yml
+++ b/.github/workflows/build-ova.yml
@@ -33,7 +33,8 @@ jobs:
       ALPINE_IMAGE_URL: https://dev.alpinelinux.org/~tomalok/alpine-cloud-images/v3.23/nocloud/x86_64/nocloud_alpine-3.23.4-x86_64-bios-cloudinit-r0.qcow2
       OVA_NAME: net-relay-alpine-x86_64.ova
       RAW_NAME: net-relay-alpine-x86_64.raw
-      IMAGE_SIZE_GIB: "1"
+      IMAGE_SIZE_MIB: "384"
+      MIN_ROOT_FREE_MIB: "80"
       INSTALLER_ARCHIVE_NAME: net_relay-main.tar.gz
       RELAY_AMD64_PACKAGE: netbird-relay-linux-amd64.tar.gz
       RELAY_ARM64_PACKAGE: netbird-relay-linux-arm64.tar.gz
@@ -209,7 +210,7 @@ jobs:
         run: |
           export LIBGUESTFS_BACKEND=direct
           curl -fsSL "$ALPINE_IMAGE_URL" -o ova-build/alpine.qcow2
-          qemu-img create -f qcow2 ova-build/net-relay-alpine.qcow2 "${IMAGE_SIZE_GIB}G"
+          qemu-img create -f qcow2 ova-build/net-relay-alpine.qcow2 "${IMAGE_SIZE_MIB}M"
           sudo guestfish --rw -a ova-build/alpine.qcow2 -a ova-build/net-relay-alpine.qcow2 <<'EOF'
           run
           part-init /dev/sdb mbr
@@ -297,7 +298,7 @@ jobs:
             </References>
             <DiskSection>
               <Info>Virtual disk information</Info>
-              <Disk ovf:diskId="disk1" ovf:fileRef="file1" ovf:capacity="${IMAGE_SIZE_GIB}" ovf:capacityAllocationUnits="byte * 2^30" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized"/>
+              <Disk ovf:diskId="disk1" ovf:fileRef="file1" ovf:capacity="${IMAGE_SIZE_MIB}" ovf:capacityAllocationUnits="byte * 2^20" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized"/>
             </DiskSection>
             <NetworkSection>
               <Info>Logical networks used in the package</Info>
@@ -326,6 +327,13 @@ jobs:
       - name: Verify RAW BIOS bootability
         run: |
           qemu-img info "release/${RAW_NAME}"
+          virt-df -m -a "release/${RAW_NAME}" | tee ova-build/raw-df.txt
+          root_available_mib="$(awk '$1 ~ /\/dev\/sda1$/ {print int($4)}' ova-build/raw-df.txt)"
+          if [ -z "${root_available_mib}" ] || [ "${root_available_mib}" -lt "${MIN_ROOT_FREE_MIB}" ]; then
+            cat ova-build/raw-df.txt
+            echo "::error::RAW root partition must keep at least ${MIN_ROOT_FREE_MIB} MiB free before cloud first boot."
+            exit 1
+          fi
           sudo sfdisk --verify "release/${RAW_NAME}"
           if ! sudo fdisk -l "release/${RAW_NAME}" | grep -Eq '^[^[:space:]]+[0-9]+[[:space:]]+\*'; then
             sudo fdisk -l "release/${RAW_NAME}"
